# ==============================================================================
# Minimal Makefile
# To compile, run 'make'.
# To clean, run 'make clean'.
# ==============================================================================

# Default target to compile the program.
all: joystick

joystick: joystick.c
	gcc -Wall -g joystick.c -o joystick

# Phony target to clean up compiled files.
.PHONY: clean
clean:
	rm -f joystick
